;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Quest.Step.FireSigilActivated",NewTagName="Quest.Step.FireEmpowered")
+GameplayTagRedirects=(OldTagName="Quest.Step.WindSigilActivated",NewTagName="Quest.Step.WindEmpowered")
+GameplayTagRedirects=(OldTagName="Quest.Step.WaterSigilActivated",NewTagName="Quest.Step.WaterEmpowered")
+GameplayTagRedirects=(OldTagName="Quest.Step.SigilCompleted",NewTagName="Quest.Step.TutorialComplete")
+GameplayTagRedirects=(OldTagName="Quest.Main.OpenYourEyes",NewTagName="Quest.Main.WakingFromTheDeep")
+GameplayTagRedirects=(OldTagName="Quest.Main.ACenturyLater",NewTagName="Quest.Main.AStoryLeftBehind")
+GameplayTagRedirects=(OldTagName="Quest.Main.ReclaimFire",NewTagName="Quest.Main.TheCorruptedGuardianFire")
+GameplayTagRedirects=(OldTagName="Quest.Main.ReclaimWind",NewTagName="Quest.Main.TheCorruptedGuardianWind")
+GameplayTagRedirects=(OldTagName="Quest.Main.ReclaimWater",NewTagName="Quest.Main.TheCorruptedGuardianWater")
+GameplayTagRedirects=(OldTagName="SystemMessage.Tutorial.Bornfire",NewTagName="SystemMessage.Tutorial.Bonfire")
+GameplayTagList=(Tag="Bark.Manual.Tutorial.WolvesLeft",DevComment="")
+GameplayTagList=(Tag="Enemy.SpawnGroup.TutorialWolves",DevComment="")
+GameplayTagList=(Tag="Quest.Step.ExploredVillage",DevComment="")
+GameplayTagList=(Tag="Quest.Step.FoundFireLand",DevComment="")
+GameplayTagList=(Tag="Quest.Step.FoundVillage",DevComment="")
+GameplayTagList=(Tag="Quest.Step.FoundWaterLand",DevComment="")
+GameplayTagList=(Tag="Quest.Step.FoundWindLand",DevComment="")
+GameplayTagList=(Tag="Quest.Step.WolvesDefeated",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Inaccessible",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Bonfire",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Combat",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Combat.Basic",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Combat.Choice",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.GoLeft",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Intro",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Inventory",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Map",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Merchant",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Move",DevComment="")
+GameplayTagList=(Tag="SystemMessage.Tutorial.Quest",DevComment="")

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="SystemMessage.Hint.NextArea",DevComment="System message key for next-area guidance.")

