#pragma once

#include "NativeGameplayTags.h"

namespace RetrieveGameplayTags
{
	 // ---- Init State
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

    // ---- Input
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	
    // ---- Player abilities
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Attack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_HeavyAttack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Guard);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Parry);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Dash);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Jump);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Burst);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Absorb);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Interact);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_LockOn);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_UseItem);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_SetElement_Fire);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_SetElement_Water);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_SetElement_Wind);

    // ---- Enemy / Boss abilities
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Attack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_SpecialAttack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_PatternAttack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_PhaseTransition);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_Groggy);

    // ---- Common abilities
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Common_Die);

    // ---- Player state
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Normal);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Combat);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Attacking);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Dodging);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Guarding);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Parrying);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Bursting);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Cinematic);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Staggered);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Knockdown);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Dead);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_ForcedMove);

    // ---- Enemy state
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Idle);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Chase);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Attack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_SpecialAttack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Hit);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Staggered);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Groggy);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Return);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Dead);

    // ---- Boss state
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Intro);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Combat);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_PatternAttack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_PhaseTransition);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Groggy);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Staggered);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Dead);

    // ---- Status state
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Status_Burn);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Status_Cold);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Status_Vulnerable);

    // ---- Combat micro-state
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combo_Open);

    // ---- Gauge state
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Gauge_Full);

	// ---- Attack type
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_Normal);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_Heavy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_BossHeavy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_Unblockable);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_Parryable);
	
    // ---- Elements
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Fire);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Water);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Wind);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Corruption);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_None);

    // ---- Weapon
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Unarmed);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_SwordShield);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_DualBlade);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Staff);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Grade_Low);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Grade_Mid);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Grade_High);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Affinity_Fire);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Affinity_Water);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Affinity_Wind);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Affinity_None);

    // ---- Cosmetic (외형 차원, Layer 매칭용)
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Gender_Male);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Gender_Female);
	
    // ---- Lock-on
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockOn_Active);

    // ---- Animation locks
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Lock_Rotation);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Lock_Movement);

    // ---- Gameplay events: combat
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ComboFinisher);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Hit);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Hit_Normal);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Hit_Heavy);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Parry_Success);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Guard_Broken);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Dodge_Success);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_DodgeCounter_Success);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_WeakPointHit);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_Impact);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_Impact_Begin);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess_Light);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess_Heavy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess_WeakPoint);
	
    // ---- Gameplay events: boss / pattern counter
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Boss_PatternCast);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Boss_PhaseTransition);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_PatternCounterWindow);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_PatternCountered);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_GroggyTrigger);

    // ---- Gameplay events: enemy combat / death
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_Attack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_Die);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Boss_Die);

    // ---- Gameplay events: element / core / item
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Element_Unlock);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Element_ModeChange);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Core_Drop);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Core_Absorb);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Item_Used);

    // ---- Input routing tags
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_UseItem_Slot1);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_UseItem_Slot2);

    // ---- Item
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Currency);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Draught_Fire);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Draught_Water);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Draught_Wind);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_EmptyFlask);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Fire);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Water);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Wind);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Currency_Basic);

    // ---- Message channels
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Session_StateChanged);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Combat_Hit);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Combat_DamageDealt);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_ElementGauge_SlotChanged);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_ElementGauge_Full);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_ElementGauge_Burst);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Quest_GuardianDefeated);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_World_OutpostActivated);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Player_Died);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Monster_Died);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Game_QueenDefeated);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Enemy_PlayerSpotted);
	
	// ---- Data
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_Mul);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_MaxHealth);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Health);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_AttackPower);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_MoveSpeed);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_IncomingDamageMultiplier);
	
	
	/*
	// ---- Hit react (피격자 반응 제어 마커 — Cue 연동용)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit_React_Stagger);

	// ---- Damage context
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Source_Player);

	// ---- Gauge state (보완)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Gauge_Empty);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Gauge_SlotReady);

	// ---- Gameplay events: combat (보완)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_HeavyAttack_Launched);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Guard_Success);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Guard_Break);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Parry_Fail);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Hit_Knockdown);
	*/

    // ---- UI VFX
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Panel_Open);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Panel_Close);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Gauge_FullPulse);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Icon_ItemAdded);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Button_Hover);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Button_Unhover);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Button_Press);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Button_Release);
    RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Tab_Switch);
}
