#pragma once

#include "NativeGameplayTags.h"

namespace RetrieveGameplayTags
{
	// ---- Init State
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	// ---- Input
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Crouch);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dash);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Zoom);

	// ---- Player abilities
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Attack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_HeavyAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_HeavyAttack_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_HeavyAttack_Water);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_HeavyAttack_Wind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_HeavyAttack_Staff);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Guard);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_GuardAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Parry);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Dash);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Blink);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Jump);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_JumpAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Burst);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Absorb);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Interact);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_LockOn);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_UseItem);
	// 원소 전환 부모 태그. 자식(Fire/Water/Wind/...)을 MatchesTag로 일괄 판정하기 위함.
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_SetElement);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_SetElement_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_SetElement_Water);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_SetElement_Wind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_RecallLumen);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_SprintAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_ParryCounter);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_BowShot);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_StanceTransition);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_EquipTransition);

	// ---- Ability families
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Attack);

	// ---- Enemy / Boss abilities
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Attack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_SelfDestruct);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_SpecialAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_PatternAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_PhaseTransition);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_Groggy);

	// ---- Common abilities
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Common_Die);

	// ---- Player state
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Normal);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Combat);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_WeaponSheathed);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_StanceBusy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Attacking);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Dodging);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Guarding);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Parrying);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_CanCounter);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_UsingHeavyAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Bursting);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Cinematic);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Staggered);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Knockdown);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Dead);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_ForcedMove);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_ForcedKnockback);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Sprinting);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Crouching);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Swimming);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Swimming_UnderWater);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Modal_Dialogue);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Modal_Cinematic);

	// ---- Cooldown
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Player_Parry);

	// ---- Action state
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Action_HighMobility);

	// ---- Enemy state
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Idle);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Chase);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Attack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_SpecialAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Hit);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Staggered);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Groggy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Return);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Dead);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_SelfDestructing);

	// ---- Immune
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Immune_Knockback);

	// ---- Boss state
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Intro);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Combat);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_PatternAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_PhaseTransition);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Groggy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Staggered);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Boss_Dead);

	// ---- Status state
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Status_Burn);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Status_Cold);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Status_ColdReaction);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Status_Vulnerable);

	// ---- Combat micro-state
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combo_Open);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack_CancelOpen);

	// ---- Gauge state
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Gauge_Full);

	// ---- Attack type
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_Normal);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_Heavy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_BossHeavy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_Unblockable);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Type_Parryable);

	// ---- Attack property
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Property);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack_Property_GuardBreak);

	// ---- Hit react type
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Type);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Type_Flinch);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Type_Stagger);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Type_Knockdown);

	// ---- Elements
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Water);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Wind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_Corruption);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Element_None);

	// ---- Weapon
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Unarmed);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_SwordShield);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_DualBlade);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Staff);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Bow);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Grade_Low);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Grade_Mid);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Grade_High);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Affinity_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Affinity_Water);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Affinity_Wind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Affinity_None);

	// ---- Equipment
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Slot_Head);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Slot_Chest);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Slot_Hands);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Slot_Legs);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equipment_Slot_Feet);

	// ---- Cosmetic (외형 차원, Layer 매칭용)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Gender_Male);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Gender_Female);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Head);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Torso);

	// ---- Cosmetic Part (granular, Sidekick PartType 단위 — modular spawn slot)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Hair);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Eyebrow_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Eyebrow_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Eye_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Eye_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Ear_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Ear_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_FacialHair);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Arm_Upper_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Arm_Upper_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Arm_Lower_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Arm_Lower_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Hand_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Hand_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Hips);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Leg_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Leg_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Foot_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Foot_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Head);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Face);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Back);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Hips_Front);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Hips_Back);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Hips_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Hips_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Shoulder_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Shoulder_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Elbow_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Elbow_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Knee_Left);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Attachment_Knee_Right);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Nose);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Teeth);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Tongue);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cosmetic_Part_Wrap);

	// ---- Lock-on
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockOn_Active);

	// ---- Animation locks
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Lock_Rotation);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Animation_Lock_Movement);

	// ---- ALS Locomotion Actions (Retrieve 확장)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LocomotionAction_Attack);

	// ---- Gameplay events: combat
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ComboFinisher);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Hit);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Hit_Normal);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Hit_Heavy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_Hit);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Parry_Success);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Parry_Counter);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Parried);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Guard_Success);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Guard_Broken);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Dodge_Success);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_DodgeCounter_Success);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_WeakPointHit);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_Impact);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_Impact_Begin);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess_Light);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess_Heavy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess_Burst);
	// GE_Burn(도트) 전용 강도 태그 — 버스트 직격과 다른 DT_HitFeedback 행으로 플로터를 따로 띄운다.
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess_Burn);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Attack_HitSuccess_WeakPoint);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reaction_Finished);

	// ---- Gameplay events: stance (draw / sheathe)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Player_DrawWeapon);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Player_SheatheWeapon);

	// ---- Gameplay events: equip (equip / unequip)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Player_EquipWeapon);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Player_UnequipWeapon);
	
	// ---- Gameplay events: boss / pattern counter
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Boss_PatternCast);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Boss_PhaseTransition);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_PatternCounterWindow);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_PatternCountered);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_GroggyTrigger);

	// ---- Gameplay events: enemy combat / death
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_Attack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_Die);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Boss_Die);
	
	// ---- Gameplay events: enemy combat : special attack
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_Projectile);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_ProjectileRapid);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_ProjectileRain);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_ProjectileHoming);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_ProjectileSpread);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_Acceleration);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_DashAttack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_AerialDive);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_GroundHazard);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_GroundHazards);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_WaterPillar);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_IcePillar);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_RoarKnockBack);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_SummonUndeads);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SelfDestruct);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_Wave);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_Tornado);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_FireExplosiveSlamCombo);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_WindRetreatSlash);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_WindRetreatSlashStart);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Enemy_SpecialAttack_WindRetreatSlashFire);

	// ---- Gameplay events: element / core / item
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Element_Unlock);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Element_ModeChange);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Core_Drop);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Core_Absorb);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Item_Used);

	// ---- Input routing tags
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_UseItem_Slot1);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_UseItem_Slot2);

	// ---- Item
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Currency);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Draught_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Draught_Water);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Draught_Wind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_EmptyFlask);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Water);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Wind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Currency_Basic);

	// ---- UI Buff
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Item);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Item_FireBoost);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Item_WaterBoost);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Item_WindBoost);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Burst);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Burst_FireSlash);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Burst_WaterVortex);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Burst_WindSlash);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Absorb);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Absorb_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Absorb_Water);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Buff_Absorb_Wind);

	// ---- Message channels
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Session_StateChanged);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Combat_Hit);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Combat_DamageDealt);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_ElementGauge_SlotChanged);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_ElementGauge_Full);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_ElementGauge_Burst);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Item_ElementBuff);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_World_OutpostActivated);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Player_Rested);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Player_Died);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Monster_Died);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Game_QueenDefeated);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Enemy_PlayerSpotted);

	// ---- Message channels: UI Buff
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_UI_Buff_Apply);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_UI_Buff_Remove);

	// ---- Message channels: UI Skill popup
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_UI_SkillActivated);

	// ---- Message channels: Quest
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Quest_GuardianDefeated);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Quest_StepChanged);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Quest_SealUnlocked);

	// ---- Message channels: Lumen command
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Lumen_Command_ToggleWait);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Lumen_Command_Recall);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Lumen_Mode_Changed);

	// ---- Message channels: Shop
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Shop_OpenShop);

	// ---- Message channels: Dialogue / Cinematic
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Dialogue_LineRequested);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Cinematic_Changed);
	
	// ---- Message channels: UI Bark / Dialogue suppression / System Message
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_UI_BarkRequested);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_UI_DialogueChanged);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_UI_SystemMessage);

	// ---- Data
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_Mul);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Knockback_Strength);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Knockback_UpwardStrength);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Knockback_CancelTargetActions);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_MaxHealth);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Health);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_AttackPower);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_MoveSpeed);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_IncomingDamageMultiplier);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Defense);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_GuardDamageReduction);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_AttackSpeedMultiplier);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_MaxStamina);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Stamina);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_StaminaRegenRate);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Weapon_AttackPower);
	// 방어구 장착 시 Defense 가산에 사용하는 SetByCaller 태그
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Armor_Defense);

	// ---- Gameplay cues: Heavy attack
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HeavyAttack_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HeavyAttack_Water);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HeavyAttack_Water_Active);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HeavyAttack_Wind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HeavyAttack_NoSlot);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Sigil_Burst);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Sigil_Fire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Sigil_Wind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Sigil_Water);

	// ---- Gameplay cues: Staff
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Staff_Cast);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Staff_Impact);

	// ---- Gameplay cues: Parry
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Parry_Success);

	// ---- Gameplay cues: Status (지속 상태이상 — GE의 GameplayCue 컴포넌트로 Add/Remove)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Status_Burn);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Status_Cold);

	// ---- Gameplay cues: Combat (타격 임팩트 — 데미지 GE의 GameplayCue 컴포넌트로 실행)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Combat_Hit);

	// ---- UI VFX
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Panel_Open);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Panel_Close);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Gauge_FullPulse);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Icon_ItemAdded);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Button_Hover);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Button_Unhover);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Button_Press);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Button_Release);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_VFX_Tab_Switch);

	// ---- Quest steps
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_Awakening);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_TutorialComplete); // 구: Quest_Step_SigilCompleted
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_FireGuardianDefeated);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_WindGuardianDefeated);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_WaterGuardianDefeated);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_FireEmpowered); // 구: Quest_Step_FireSigilActivated
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_WindEmpowered); // 구: Quest_Step_WindSigilActivated
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_WaterEmpowered); // 구: Quest_Step_WaterSigilActivated
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_SealUnlocked);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_SealOpened);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_QueenDefeated);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Step_GameComplete);

	// ---- Quest definitions (DT_Quest QuestIds)
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Main_OpenYourEyes);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Main_ACenturyLater);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Main_ReclaimFire);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Main_ReclaimWater);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Main_ReclaimWind);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quest_Main_StormTheCastle);

	// ---- Dialogue
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Speaker_Lumen);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Speaker_NPC_General);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Speaker_NPC_Townsfolk);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_ShopNPC_OpenShop);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_ShopNPC_Buy);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_ShopNPC_Sell);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_Lumen_Imprint);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_Lumen_About);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_Lumen_FollowWait);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_Lumen_FireSigil);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_Lumen_WindSigil);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Topic_Lumen_WaterSigil);
	
	// ---- Bark
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bark_Category_Ambient);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bark_Category_Tutorial);

	// --- Enemy Types
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Type_Normal);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Type_Epic);
	RETRIEVE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Type_Boss);
}
